### ISSUE TITLE
DeprecationWarning: pkg_resources is deprecated as an API

### ISSUE THREAD

**Issue by Justintime50** [Justintime50/pip-tree#8]
```
venv/lib/python3.11/site-packages/pkg_resources/__init__.py:121
  /Users/jhammond/git/personal/pip-tree/venv/lib/python3.11/site-packages/pkg_resources/__init__.py:121: DeprecationWarning: pkg_resources is deprecated as an API
    warnings.warn("pkg_resources is deprecated as an API", DeprecationWarning)
```

**Comment by Borda** [comment]
This would mean finding a replacement for `pkg_resources.find_distributions`

Some pointer:
- https://docs.python.org/3/library/importlib.metadata.html#extending-the-search-algorithm
- https://github.com/python/importlib_metadata/issues/131

**Comment by Justintime50** [comment]
Hey @Borda, thanks for the pointers! I've been looking at those actually but haven't had a chance yet to play with the code, would you want to take a crack at it? In a perfect world we'd drop in the new `importlib` package with as minimal code changes as needed to get the same results.
